export const RAG_ROLLOUT_GUARDS = {
  NONE: 'NONE',
  FEATURE_FLAG_DISABLED: 'FEATURE_FLAG_DISABLED',
  TENANT_NOT_ALLOWED: 'TENANT_NOT_ALLOWED',
  CATEGORY_NOT_ALLOWED: 'CATEGORY_NOT_ALLOWED',
  REQUIRED_METADATA_MISSING: 'REQUIRED_METADATA_MISSING'
} as const;

export type RagRolloutGuard = typeof RAG_ROLLOUT_GUARDS[keyof typeof RAG_ROLLOUT_GUARDS];
